version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: creditcore-db
    environment:
      POSTGRES_DB: creditcore
      POSTGRES_USER: credituser
      POSTGRES_PASSWORD: creditpass
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: